services:
  - type: web
    name: Economy-Simulator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: src/backend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false 