services:
  - type: web
    name: economy-simulator-backend
    env: node
    buildCommand: cd src/backend && npm install && npm run build
    startCommand: cd src/backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://economy-simulator-frontend.onrender.com 